# Use official Golang 1.22 image for ARM64 (Mac M3 Pro compatible)
FROM --platform=linux/arm64 golang:1.22 AS builder

WORKDIR /app

# Copy source code into the container
COPY bin/api_gateway api_gateway
COPY api_gateway/config.json config.json

# Expose the /app/api_gateway port
EXPOSE 8084

# Run the /app/api_gateway
CMD ["/app/api_gateway"]
