# Use official Golang 1.22 image for ARM64 (Mac M3 Pro compatible)
FROM --platform=linux/arm64 golang:1.22 AS builder

WORKDIR /app

# Copy source code into the container
COPY bin/microservice /microservice

# Download dependencies and build
# COPY go.mod go.sum ./
# RUN go mod download
# COPY *.go ./

# Build the binary for Linux ARM64
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o /microservice .

# Expose the microservice port
EXPOSE 8081

# Run the microservice
CMD ["/microservice"]
